[project]
name = "train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "seonwoo0808", email = "me@ptg.kr" }
]
requires-python = "==3.12.12"
dependencies = [
    "numba==0.67.0",
    "numpy==2.5.3",
    "pyarrow==25.0.1",
    "tensorflow==2.20.0",
    "keras==3.15.1",
]

[project.scripts]
train = "train:main"

[build-system]
requires = ["uv_build==0.12.1"]
build-backend = "uv_build"
